# Generated by Django 3.0.5 on 2021-02-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='00/00', max_length=100)),
                ('time', models.CharField(default='00:00', max_length=100)),
                ('state', models.CharField(default='karnatak', max_length=100)),
                ('ci', models.CharField(default='-', max_length=100)),
                ('cf', models.CharField(default='-', max_length=100)),
                ('cured', models.IntegerField(blank=True)),
                ('deaths', models.IntegerField(blank=True)),
                ('confirmed', models.IntegerField(blank=True)),
            ],
        ),
    ]
